site_name: Empirical Dynamic Modeling (edm) Stata Package

nav:
  - Home: index.md
  - Time-delayed embedding: time-delayed-embedding.md
  - Stata Help File: api.md

theme:
  name: material
  hljs_languages:
    - stata

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js