site_name: Empirical Dynamic Modeling (edm) Stata Package

nav:
  - Home: index.md
  - Examples:
    - Chicago crime/temperature (WIP): chicago.md
    - Logistic map (WIP): logistic-map.md 
  - How does it work?:
    - Time-delayed embedding: time-delayed-embedding.md
    - The explore subcommand: explore.md
    - The xmap subcommand: xmap.md
    - Adding variables to manifold: adding-to-manifold.md
    - Missing data: missing-data.md
    - Coprediction: coprediction.md
  - GPU Acceleration: gpu.md
  - Automated workflows: automated-workflows.md
  - Stata Help File: api.md

theme:
  name: material
  
  # These are the default colours
  palette:
    primary: indigo
    accent: indigo
    
  font:
    text: Alegreya Sans
  
  hljs_languages:
    - stata

markdown_extensions:
  - admonition
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/sliders.css
  - stylesheets/fix-mathjax-font-subscript-bug.css
  
extra_javascript:
  - assets/setup-mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js